### ISSUE TITLE
Add categories based on Languages & Frameworks

### ISSUE THREAD

**Issue by MaheshPawar97** [ErikCH/DevYouTubeList#80]
We can create more categories based on languages, frameworks.

**Comment by sukhchainn** [comment]
@MaheshPawar97 creating categories based on frameworks is unnecessary because there aren't many YouTube channels which only focus on a single framework and not a language. The model I'm working on focuses on four main categories namely (C/C++, PHP, JavaScript, other).

If you have strong reasons for having more categories than these then please consider that I'm trying to make it easier for others to contribute to this list through scripts, so your reasons should be strong.

**Comment by MaheshPawar97** [comment]
Looking forward to seeing your work.
